export const JOIN_ROOM_REQUEST = 'JOIN_ROOM_REQUEST';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';

export const LEAVE_ROOM_REQUEST = 'LEAVE_ROOM_REQUEST';
export const LEAVE_ROOM_SUCCESS = 'LEAVE_ROOM_SUCCESS';

export const LIST_ROOMS_REQUEST = 'LIST_ROOMS_REQUEST';
export const LIST_ROOMS_SUCCESS = 'LIST_ROOMS_SUCCESS';

export const SET_ATTEMPTED_ROOM = 'SET_ATTEMPTED_ROOM';
export const CLEAR_ATTEMPTED_ROOM = 'CLEAR_ATTEMPTED_ROOM';

export const INCREMENT_LIFE = 'INCREMENT_LIFE';
export const DECREMENT_LIFE = 'DECREMENT_LIFE';

export const SET_LIFE_REQUEST = 'SET_LIFE_REQUEST';

export const WS_ERROR = 'WS_ERROR';
export const UPDATE_USERS = 'UPDATE_USERS';

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_TOAST = 'CLEAR_TOAST';
