export const INVALID_PASS = 'INVALID_PASS';
export const MISSING_ROOM_ID = 'MISSING_ROOM_ID';
export const MISSING_USER_ID = 'MISSING_USER_ID';
export const USER_EXISTS = 'USER_EXISTS';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const ROOM_FULL = 'ROOM_FULL';
export const CONNECTION_LOST = 'CONNECTION_LOST';

export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
